name: "Continuous Integration"

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: "always"
jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
  ubuntu:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
